#version 450

// This defines the local workgroup size: 16 threads in X, 1 in Y and Z
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set=0, binding=0) readonly buffer Input {
    uint input_data[];
};

layout(binding = 1, rgba8) uniform image2D outputImage;

void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = vec4(pixelCoords.x / 1600.0, pixelCoords.y / 1200.0, 0.0, 1.0);
    imageStore(outputImage, pixelCoords, color);
}
