#version 450

// This defines the local workgroup size: 16 threads in X, 1 in Y and Z
layout(local_size_x = 16, local_size_y = 1, local_size_z = 1) in;

layout(set=0, binding=0) readonly buffer Input {
    uint input_data[];
};

layout(set=0, binding=1) writeonly buffer Output {
    uint output_data[];
};

layout(set=0, binding=2) uniform UniformArgs {
    uint multiplier;
} uniform_args;

layout(push_constant) uniform PushArgs {
    uint someValue;
} push_args;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    uint val = input_data[idx];
    output_data[idx] = val * uniform_args.multiplier;
}
